os:
- linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev

language: generic

cache:
  # Cache the global cargo directory and the local binary dependencies
  directories:
  - /home/travis/.cargo
  - target/debug/deps

before_script:
# Compute the rust version we use. We do not use "language: rust" to have more control here.
- RUST_TOOLCHAIN=nightly
# install Rust
- curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain "$RUST_TOOLCHAIN"
- export PATH=$HOME/.cargo/bin:$PATH
- rustc --version
# install formatter
- rustup component add rustfmt-preview
# install linter
- rustup component add clippy-preview
# install code coverage tool
- RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || true

script:
# Exit immediately if a command exits with a non-zero status.
- set -e
# Run format checks
- cargo fmt --all -- --check
# Run lint checks
- cargo clippy -- -D warnings
# Build
- cargo build
# Run unit and integration tests
- cargo test
# Run mirai on itself
- cargo uninstall mirai || true
- cargo install --debug --path .
- cargo clean -p mirai
- RUSTC_WRAPPER=mirai cargo build
- cargo uninstall mirai

after_success:
- MIRAI_LOG=info cargo tarpaulin --out Xml
- bash <(curl -s https://codecov.io/bash)
