os: osx
language: rust
rust:
- nightly-2019-08-27

before_install:
- if [ ${TRAVIS_OS_NAME} == "osx" ]; then curl -L https://github.com/mozilla/grcov/releases/download/v0.4.3/grcov-osx-x86_64.tar.bz2 | tar jxf -; fi

before_script:
# install formatter
- rustup component add rustfmt-preview
# install linter
- rustup component add clippy-preview
# install audit
- cargo install --force cargo-audit || true
# install z3
- if [ ${TRAVIS_OS_NAME} == "osx" ]; then cp binaries/libz3.dylib /usr/local/lib; fi

script:
# Exit immediately if a command exits with a non-zero status.
- set -e
# Audit dependencies
- cargo audit
# Run format checks
- cargo fmt --all -- --check
# Run lint checks
- cargo clippy -- -D warnings
# Build
- cargo build
# Run unit and integration tests
- RUST_BACKTRACE=1 cargo test
# Run code coverage tests
- |
  if [ ${TRAVIS_OS_NAME} == "osx" ]
  then 
    export CARGO_INCREMENTAL=0
    export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
    cargo build
    cargo test
    zip -0 ccov.zip `find . \( -name "mirai*.gc*" \) -print`
    ./grcov ccov.zip --ignore-not-existing --llvm --ignore-dir "/*" -t lcov  > lcov.info
    bash <(curl -s https://codecov.io/bash) -f lcov.info
  fi
