[workspace]

members = [
    "annotations",
    "checker",
    "standard_contracts",
    "examples/taint",
    "examples/shopping_cart"
]

[profile.release]
debug = true

[profile.bench]
debug = true
