[package]
name = "shopping_cart"
version = "0.1.0"
authors = ["Wolfgang Grieskamp <wrwg@fb.com>"]
edition = "2018"

[[bin]]
name = "shopping_cart"

[dependencies]
mirai-annotations = "1.8.0"
contracts = "0.4.0"