[env]
MIRAI_FLAGS = { value = "--diag=paranoid --single_func=pallet_example_offchain_worker.mirai.mirai_check.code_to_analyze"}
#MIRAI_FLAGS = { value = "--diag=paranoid", force = true }
#MIRAI_LOG = { value = "debug", force = true }