name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Run Clippy
        run: |
          cargo clippy --no-default-features --all-targets -- -D warnings

  tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Execute tests
        run: |
          cargo test --all -- --test-threads=1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests"

      - name: Setup grcov
        uses: actions-rs/grcov@v0.1

      - name: Run grcov
        run: |
          zip -0 cov.zip $(find . -name "mirai*.gc*" -print)
          grcov cov.zip -s . -t lcov --llvm --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "lcov.info"

  mirai_on_mirai_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Install MIRAI
        run: |
          cargo install --force --path ./checker --no-default-features

      - name: Run MIRAI on MIRAI
        run: |
          cargo mirai --no-default-features

  mirai_on_mirai_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Install MIRAI
        run: |
          cargo install --force --path ./checker

      - name: Run MIRAI on MIRAI
        run: |
          cargo mirai --no-default-features

  mirai_on_mirai_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Install MIRAI
        run: |
          cargo install --force --path ./checker

      - name: Run MIRAI on MIRAI
        run: |
          cargo mirai --no-default-features

